spring.application.name=url-shortner

spring.config.import=optional:file.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5433/url-shortner
spring.datasource.username=khubaib
spring.datasource.password=khubaib

spring.jpa.hibernate.ddl-auto=validate
spring..jpa.open-in-view=false

spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true
